# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cretin
version:      0.5b5
version_from: lib/Cretin.pm
installdirs:  site
requires:
    CDDB:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
